# Generated by Django 6.0.4 on 2026-05-01 06:04

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото "Про нас"'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=wagtail.fields.RichTextField(default='', verbose_name='Текст "Про нас"'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок "Про нас"'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='achievements_title',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок досягнень'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_address',
            field=models.CharField(default='', max_length=300, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_phone',
            field=models.CharField(default='', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_text',
            field=wagtail.fields.RichTextField(default='', verbose_name='Текст футера'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_bg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фон Hero'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок Hero'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок Hero'),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Фото')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
