# Generated by Django 6.0.4 on 2026-05-01 07:00

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_about_image_homepage_about_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text_1',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Текст "Про нас" 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text_2',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Текст "Про нас" 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text_3',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Текст "Про нас" 3'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок "Про нас"'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='achievements_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок досягнень'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contact_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_text',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Текст футера'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок Hero'),
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
