# Generated by Django 6.0.4 on 2026-05-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='location_subtitle',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Підзаголовок адреси'),
        ),
    ]
