# Generated by Django 6.0.4 on 2026-05-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_location_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_btn_text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Текст кнопки запису'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_section_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок секції контактів'),
        ),
    ]
