# Generated by Django 6.0.4 on 2026-05-01 18:08

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_contact_btn_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about_text_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_text_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_text_3',
        ),
        migrations.CreateModel(
            name='AboutTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', wagtail.fields.RichTextField(verbose_name='Текст')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_texts', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
