# Generated by Django 6.0.4 on 2026-05-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_homepage_about_text_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок футера'),
        ),
    ]
