# Generated by Django 6.0.4 on 2026-05-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_footer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='video_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок відео'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_url',
            field=models.URLField(blank=True, default='', verbose_name='Посилання на відео (YouTube)'),
        ),
    ]
