# Generated by Django 6.0.4 on 2026-05-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepage_video_title_homepage_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='video_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='video_url',
        ),
    ]
